# Generated by Django 4.2.16 on 2024-12-25 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="カテゴリー名")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="写真"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name_plural": "Category",
            },
        ),
        migrations.CreateModel(
            name="DiningTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_for_internal",
                    models.CharField(max_length=64, verbose_name="卓名（店舗管理用）"),
                ),
                (
                    "name_for_customer",
                    models.CharField(max_length=64, verbose_name="卓名（HP表示用）"),
                ),
                (
                    "min_people",
                    models.IntegerField(
                        choices=[
                            ("", "選択してください"),
                            (1, "1名"),
                            (2, "2名"),
                            (3, "3名"),
                            (4, "4名"),
                            (5, "5名"),
                            (6, "6名"),
                            (7, "7名"),
                            (8, "8名"),
                            (9, "9名"),
                            (10, "10名"),
                            (11, "11名"),
                            (12, "12名"),
                            (13, "13名"),
                            (14, "14名"),
                            (15, "15名"),
                            (16, "16名"),
                            (17, "17名"),
                            (18, "18名"),
                            (19, "19名"),
                            (20, "20名"),
                            (21, "21名"),
                            (22, "22名"),
                            (23, "23名"),
                            (24, "24名"),
                            (25, "25名"),
                            (26, "26名"),
                            (27, "27名"),
                            (28, "28名"),
                            (29, "29名"),
                            (30, "30名"),
                            (31, "31名"),
                            (32, "32名"),
                            (33, "33名"),
                            (34, "34名"),
                            (35, "35名"),
                            (36, "36名"),
                            (37, "37名"),
                            (38, "38名"),
                            (39, "39名"),
                            (40, "40名"),
                            (41, "41名"),
                            (42, "42名"),
                            (43, "43名"),
                            (44, "44名"),
                            (45, "45名"),
                            (46, "46名"),
                            (47, "47名"),
                            (48, "48名"),
                            (49, "49名"),
                            (50, "50名"),
                        ],
                        default="",
                        verbose_name="最少人数",
                    ),
                ),
                (
                    "max_people",
                    models.IntegerField(
                        choices=[
                            ("", "選択してください"),
                            (1, "1名"),
                            (2, "2名"),
                            (3, "3名"),
                            (4, "4名"),
                            (5, "5名"),
                            (6, "6名"),
                            (7, "7名"),
                            (8, "8名"),
                            (9, "9名"),
                            (10, "10名"),
                            (11, "11名"),
                            (12, "12名"),
                            (13, "13名"),
                            (14, "14名"),
                            (15, "15名"),
                            (16, "16名"),
                            (17, "17名"),
                            (18, "18名"),
                            (19, "19名"),
                            (20, "20名"),
                            (21, "21名"),
                            (22, "22名"),
                            (23, "23名"),
                            (24, "24名"),
                            (25, "25名"),
                            (26, "26名"),
                            (27, "27名"),
                            (28, "28名"),
                            (29, "29名"),
                            (30, "30名"),
                            (31, "31名"),
                            (32, "32名"),
                            (33, "33名"),
                            (34, "34名"),
                            (35, "35名"),
                            (36, "36名"),
                            (37, "37名"),
                            (38, "38名"),
                            (39, "39名"),
                            (40, "40名"),
                            (41, "41名"),
                            (42, "42名"),
                            (43, "43名"),
                            (44, "44名"),
                            (45, "45名"),
                            (46, "46名"),
                            (47, "47名"),
                            (48, "48名"),
                            (49, "49名"),
                            (50, "50名"),
                        ],
                        default="",
                        verbose_name="最大人数",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name_plural": "Dining Table",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="メニュー名")),
                ("description", models.TextField(verbose_name="メニュー説明")),
                (
                    "price",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="価格（一名分）"
                    ),
                ),
                ("available_from", models.TimeField(verbose_name="提供開始時間")),
                ("available_end", models.TimeField(verbose_name="提供終了時間")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="写真"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=32, verbose_name="郵便番号")),
                ("shop_name", models.CharField(max_length=64, verbose_name="店舗名")),
                ("address", models.CharField(max_length=128, verbose_name="住所")),
                ("phone", models.CharField(max_length=32, verbose_name="電話番号")),
                (
                    "owner_name",
                    models.CharField(max_length=64, verbose_name="代表者名"),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="メールアドレス",
                    ),
                ),
                ("description", models.CharField(max_length=128, verbose_name="説明")),
                (
                    "min_price",
                    models.IntegerField(blank=True, null=True, verbose_name="最低価格"),
                ),
                (
                    "max_price",
                    models.IntegerField(blank=True, null=True, verbose_name="最高価格"),
                ),
                ("price", models.CharField(max_length=32, verbose_name="価格帯")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="写真"
                    ),
                ),
                (
                    "business_time",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="営業時間"
                    ),
                ),
                (
                    "close_day_of_week",
                    models.CharField(
                        blank=True, max_length=32, null=True, verbose_name="定休日"
                    ),
                ),
                ("rate", models.FloatField(default=0.0, verbose_name="レート")),
                (
                    "rate_star",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="レートスター"
                    ),
                ),
                (
                    "review_num",
                    models.IntegerField(default=0, verbose_name="レビュー数"),
                ),
                (
                    "reservation_num",
                    models.IntegerField(default=0, verbose_name="予約数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.category",
                        verbose_name="カテゴリー",
                    ),
                ),
                (
                    "shop_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="店舗オーナー",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Restaurant",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField(verbose_name="訪問日")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="コメント"),
                ),
                (
                    "rate",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                        verbose_name="レート",
                    ),
                ),
                (
                    "display_masked",
                    models.BooleanField(default="0", verbose_name="非表示フラグ"),
                ),
                ("reply", models.TextField(blank=True, null=True, verbose_name="返信")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="レビュー作成日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="レビュー更新日時"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー会員",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.restaurant",
                        verbose_name="レストラン",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Review",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="予約日")),
                (
                    "time_start",
                    models.TimeField(
                        choices=[
                            ("", "選択してください"),
                            ("12:00", "12:00"),
                            ("13:00", "13:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("18:00", "18:00"),
                            ("19:00", "19:00"),
                            ("20:00", "20:00"),
                            ("21:00", "21:00"),
                            ("22:00", "22:00"),
                        ],
                        default="",
                        verbose_name="予約開始時間",
                    ),
                ),
                (
                    "duration_min",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="制限時間（分）"
                    ),
                ),
                (
                    "number_of_people",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            ("", "選択してください"),
                            (1, "1名"),
                            (2, "2名"),
                            (3, "3名"),
                            (4, "4名"),
                            (5, "5名"),
                            (6, "6名"),
                            (7, "7名"),
                            (8, "8名"),
                            (9, "9名"),
                            (10, "10名"),
                        ],
                        default=None,
                        null=True,
                        verbose_name="人数",
                    ),
                ),
                (
                    "is_booked",
                    models.BooleanField(default="0", verbose_name="予約済みフラグ"),
                ),
                (
                    "is_dependent",
                    models.BooleanField(default="0", verbose_name="枠依存用予約フラグ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="予約受付日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="予約更新日時"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー会員",
                    ),
                ),
                (
                    "dining_table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="restaurant.diningtable",
                        verbose_name="卓情報",
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.menu",
                        verbose_name="メニュー",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.restaurant",
                        verbose_name="レストラン",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reservation",
            },
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.restaurant",
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="お気に入り登録日時"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="お気に入り更新日時"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー会員",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.restaurant",
                        verbose_name="レストラン",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Favorite",
            },
        ),
        migrations.AddField(
            model_name="diningtable",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.restaurant",
                verbose_name="レストラン",
            ),
        ),
    ]
